<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Andrew Leonard" />

<meta name="date" content="2021-07-27" />

<title>Oil Production and Land Conservation in the US</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/united.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Andrew Leonard's Portfolio</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Resume</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Examples
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="examples/oil/index.html">Wrangle Oil Production Data with R and APIs</a>
    </li>
    <li>
      <a href="examples/crp/index.html">Wrangle CRP Enrollment Data with R and Excel</a>
    </li>
    <li>
      <a href="analysis.html">Compare Oil and CRP Data with R, Tableau, and Linear Regression</a>
    </li>
    <li>
      <a href="capacity.html">Solve Capacitated Vehicle Routing Problems with Python</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://www.linkedin.com/in/andrew-leonard-83229389/">
    <span class="fa fa-linkedin"></span>
     
  </a>
</li>
<li>
  <a href="https://github.com/andrew-j-leonard">
    <span class="fa fa-github"></span>
     
  </a>
</li>
<li>
  <a href="https://stackoverflow.com/users/8623742/andrew">
    <span class="fa fa-stack-overflow"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Oil Production and Land Conservation in the US</h1>
<h4 class="author">Andrew Leonard</h4>
<h4 class="date">2021-07-27</h4>

</div>


<div id="overview" class="section level2">
<h2>Overview</h2>
<p>This document will provide a comparison of the <a href="https://andrew-j-leonard.github.io/oil.html">US EIA’s Oil Production data</a> and the <a href="https://andrew-j-leonard.github.io/crp.html">USDA’s CRP Enrollment data</a> using R Markdown, Tabeau Public, and Linear Regression models. Please refer to the other pages in this site in order to learn how to extract, clean, and save this data locally.</p>
<p>I began my career working in the ag commodities market in 2015. At the time, the <a href="https://blogs.worldbank.org/developmenttalk/what-triggered-oil-price-plunge-2014-2016-and-why-it-failed-deliver-economic-impetus-eight-charts#:~:text=The%20initial%20drop%20in%20oil,concerns%2C%20and%20shifting%20OPEC%20policies.&amp;text=This%20partly%20explains%20why%20the,subsequent%20boost%20to%20global%20activity.">price of oil was plunging</a> due to the increase in US shale oil production - obviously this had an <a href="https://www.investopedia.com/ask/answers/030415/how-does-price-oil-affect-stock-market.asp">impact on the price of agricultural commodities</a> as well.</p>
<p>The practice used in shale oil production is known as <a href="https://www.usgs.gov/faqs/what-hydraulic-fracturing?qt-news_science_products=0#">hydraulic fracturing</a> AKA “fracking” which has been around <a href="https://www.usgs.gov/faqs/when-did-hydraulic-fracturing-become-such-a-popular-approach-oil-and-gas-production?qt-news_science_products=0#qt-news_science_products">since the late 1980’s</a>. Fracking can be a controversial subject because of its <a href="https://www.usgs.gov/faqs/what-environmental-issues-are-associated-hydraulic-fracturing?qt-news_science_products=0#qt-news_science_products">effects on the environment</a> so I was curious what other facets of agriculture could be affected by shale oil production.</p>
</div>
<div id="crp-data" class="section level2">
<h2>CRP Data</h2>
<p>Let’s begin the analysis by loading the necessary packages in R.</p>
<pre class="r"><code>library(&quot;data.table&quot;)
library(&quot;htmltools&quot;)
library(&quot;ggplot2&quot;)
suppressMessages(library(&quot;here&quot;))</code></pre>
<p>Load the <a href="https://andrew-j-leonard.github.io/crp.html">CRP data</a> saved in the CSV file and view it.</p>
<pre class="r"><code>crp_fname &lt;- here(&quot;Data&quot;, &quot;usda_crp_enrollment.csv&quot;)
crp_dt &lt;- fread(crp_fname)
head(crp_dt)</code></pre>
<pre><code>##         state year    acres
## 1:    ALABAMA 1986  68508.7
## 2:     ALASKA 1986   2312.0
## 3:    ARIZONA 1986      0.0
## 4:   ARKANSAS 1986  19999.2
## 5: CALIFORNIA 1986  21953.4
## 6:   COLORADO 1986 354707.6</code></pre>
<p>Let’s rank states by the quantity of acres enrolled for the most recent date.</p>
<pre class="r"><code># Start by creating a column for the max year by state.
crp_dt[, max_year := max(year), by = state]
# Then filter where year is equal to max year.
max_crp_dt &lt;- crp_dt[year == max_year]
# now order the data by acres (descending)
setorder(max_crp_dt, -acres)
# create a number for each row
max_crp_dt[, rank := .I]
# check top 10 rows
head(max_crp_dt, 10)</code></pre>
<pre><code>##            state year   acres max_year rank
##  1:        TEXAS 2019 2811584     2019    1
##  2:       KANSAS 2019 1940899     2019    2
##  3:     COLORADO 2019 1838914     2019    3
##  4:         IOWA 2019 1745860     2019    4
##  5: NORTH DAKOTA 2019 1295115     2019    5
##  6:   WASHINGTON 2019 1191687     2019    6
##  7: SOUTH DAKOTA 2019 1142968     2019    7
##  8:     NEBRASKA 2019 1064143     2019    8
##  9:      MONTANA 2019 1059941     2019    9
## 10:    MINNESOTA 2019 1058581     2019   10</code></pre>
<p>I created a dashboard in <a href="https://public.tableau.com/views/AcresEnrolledinCRP/dashAllStates?:language=en-US&amp;:display_count=n&amp;:origin=viz_share_link">Tableau Public</a> which you can interact with below:</p>
<pre class="r"><code>read_html(&quot;crp_all_states.html&quot;)</code></pre>
<div class='tableauPlaceholder' id='viz1627505208034' style='position: relative'><noscript><a href='#'><img alt='dashAllStates ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Ac&#47;AcresEnrolledinCRP&#47;dashAllStates&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='AcresEnrolledinCRP&#47;dashAllStates' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Ac&#47;AcresEnrolledinCRP&#47;dashAllStates&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en-US' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1627505208034');                    var vizElement = divElement.getElementsByTagName('object')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.minWidth='420px';vizElement.style.maxWidth='650px';vizElement.style.width='100%';vizElement.style.minHeight='587px';vizElement.style.maxHeight='887px';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.minWidth='420px';vizElement.style.maxWidth='650px';vizElement.style.width='100%';vizElement.style.minHeight='587px';vizElement.style.maxHeight='887px';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';} else { vizElement.style.width='100%';vizElement.style.height='777px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>
<p></br></p>
</div>
<div id="oil-data" class="section level2">
<h2>Oil Data</h2>
<p>Now let’s load our <a href="https://andrew-j-leonard.github.io/oil.html">oil production data</a> and view it.</p>
<pre class="r"><code>oil_fname &lt;- here(&quot;Data&quot;, &quot;eia_oil_production.csv&quot;)
oil_dt &lt;- fread(oil_fname)
head(oil_dt)</code></pre>
<pre><code>##    state_abb  state year       date barrel barrels_per_day
## 1:        AK ALASKA 1981 1981-01-01  49789        1606.097
## 2:        AK ALASKA 1981 1981-02-01  45346        1619.500
## 3:        AK ALASKA 1981 1981-03-01  50150        1617.742
## 4:        AK ALASKA 1981 1981-04-01  48235        1607.833
## 5:        AK ALASKA 1981 1981-05-01  48977        1579.903
## 6:        AK ALASKA 1981 1981-06-01  48967        1632.233</code></pre>
<p>The oil data is aggregated by month by default so we need to aggregate it by year in order to join the data with our CRP data later.</p>
<pre class="r"><code>oil_dt &lt;- oil_dt[, .(sum_barrel = sum(barrel), avg_barrels_per_day = mean(barrels_per_day)), by = .(state_abb, state, year)]
head(oil_dt)</code></pre>
<pre><code>##    state_abb  state year sum_barrel avg_barrels_per_day
## 1:        AK ALASKA 1981     587337            1609.293
## 2:        AK ALASKA 1982     618910            1695.609
## 3:        AK ALASKA 1983     625527            1713.826
## 4:        AK ALASKA 1984     630401            1722.765
## 5:        AK ALASKA 1985     666233            1825.780
## 6:        AK ALASKA 1986     681310            1866.718</code></pre>
<p>I created another dashboard in <a href="https://public.tableau.com/views/USEIAOilProduction/dashAllStatesOil?:language=en-US&amp;:retry=yes&amp;publish=yes&amp;:display_count=n&amp;:origin=viz_share_link">Tableau Public</a> except using oil data which you can interact with below.</p>
<pre class="r"><code>read_html(&quot;oil_all_states.html&quot;)</code></pre>
<div class='tableauPlaceholder' id='viz1627575770811' style='position: relative'><noscript><a href='#'><img alt='dashAllStatesOil ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;US&#47;USEIAOilProduction&#47;dashAllStatesOil&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='USEIAOilProduction&#47;dashAllStatesOil' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;US&#47;USEIAOilProduction&#47;dashAllStatesOil&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en-US' /><param name='filter' value='publish=yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1627575770811');                    var vizElement = divElement.getElementsByTagName('object')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.minWidth='420px';vizElement.style.maxWidth='650px';vizElement.style.width='100%';vizElement.style.minHeight='587px';vizElement.style.maxHeight='887px';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.minWidth='420px';vizElement.style.maxWidth='650px';vizElement.style.width='100%';vizElement.style.minHeight='587px';vizElement.style.maxHeight='887px';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';} else { vizElement.style.width='100%';vizElement.style.height='727px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>
<p></br></p>
<p>The states we’re primarily interested in are TX, ND, SD, CO, MT, NE, NM, WY, PA, WV, OH, NY, LA, OK, and AR. <img src="Img/page1-1650px-United_States_Shale_gas_plays,_May_2011.pdf.jpg" alt="https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/United_States_Shale_gas_plays%2C_May_2011.pdf/page1-1650px-United_States_Shale_gas_plays%2C_May_2011.pdf.jpg" /> <img src="Img/202101_monthly_dry_shale.png" alt="https://www.eia.gov/naturalgas/weekly/archivenew_ngwu/2021/02_18/img/202101_monthly_dry_shale.png" /></p>
</div>
<div id="compare" class="section level2">
<h2>Compare</h2>
<p>Let’s rank states by the quantity of oil produced for the most recent year that is present in both sets of data.</p>
<pre class="r"><code>max_year &lt;- min(max(oil_dt$year), max(crp_dt$year))
max_oil_dt &lt;- oil_dt[year == max_year]
setorder(max_oil_dt, -sum_barrel)
max_oil_dt[, rank := .I]
head(max_oil_dt, 10)</code></pre>
<pre><code>##     state_abb        state year sum_barrel avg_barrels_per_day rank
##  1:        TX        TEXAS 2019    1861762           5099.4829    1
##  2:        ND NORTH DAKOTA 2019     517682           1417.6003    2
##  3:        NM   NEW MEXICO 2019     331985            909.1404    3
##  4:        OK     OKLAHOMA 2019     215582            590.4835    4
##  5:        CO     COLORADO 2019     192383            526.9238    5
##  6:        AK       ALASKA 2019     169946            465.7864    6
##  7:        CA   CALIFORNIA 2019     156350            428.5063    7
##  8:        WY      WYOMING 2019     102171            279.8368    8
##  9:        LA    LOUISIANA 2019      45897            125.7719    9
## 10:        UT         UTAH 2019      36933            101.1966   10</code></pre>
<p>Let’s compare that to the ranking for CRP.</p>
<pre class="r"><code>head(max_crp_dt, 10)</code></pre>
<pre><code>##            state year   acres max_year rank
##  1:        TEXAS 2019 2811584     2019    1
##  2:       KANSAS 2019 1940899     2019    2
##  3:     COLORADO 2019 1838914     2019    3
##  4:         IOWA 2019 1745860     2019    4
##  5: NORTH DAKOTA 2019 1295115     2019    5
##  6:   WASHINGTON 2019 1191687     2019    6
##  7: SOUTH DAKOTA 2019 1142968     2019    7
##  8:     NEBRASKA 2019 1064143     2019    8
##  9:      MONTANA 2019 1059941     2019    9
## 10:    MINNESOTA 2019 1058581     2019   10</code></pre>
<p>Let’s go ahead and filter our oil data for only these states.</p>
<pre class="r"><code>fracking_states &lt;- c(&quot;TX&quot;, &quot;ND&quot;, &quot;SD&quot;, &quot;CO&quot;, &quot;MT&quot;, &quot;NE&quot;, &quot;NM&quot;, &quot;WY&quot;, &quot;PA&quot;, &quot;WV&quot;, &quot;OH&quot;, &quot;NY&quot;, &quot;LA&quot;, &quot;OK&quot;, &quot;AR&quot;)
oil_dt &lt;- oil_dt[state_abb %in% fracking_states]</code></pre>
<p>I created another dashboard in <a href="https://public.tableau.com/views/AcresEnrolledinCRP/dashFrackingStates?:language=en-US&amp;:display_count=n&amp;:origin=viz_share_link">Tableau Public</a> for CRP data in fracking states only which you can interact with below:</p>
<pre class="r"><code>read_html(&quot;crp_fracking_states.html&quot;)</code></pre>
<div class='tableauPlaceholder' id='viz1627503726534' style='position: relative'><noscript><a href='#'><img alt='dashFrackingStates ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Ac&#47;AcresEnrolledinCRP&#47;dashFrackingStates&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='AcresEnrolledinCRP&#47;dashFrackingStates' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Ac&#47;AcresEnrolledinCRP&#47;dashFrackingStates&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en-US' /><param name='filter' value='publish=yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1627503726534');                    var vizElement = divElement.getElementsByTagName('object')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.minWidth='420px';vizElement.style.maxWidth='650px';vizElement.style.width='100%';vizElement.style.minHeight='587px';vizElement.style.maxHeight='887px';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.minWidth='420px';vizElement.style.maxWidth='650px';vizElement.style.width='100%';vizElement.style.minHeight='587px';vizElement.style.maxHeight='887px';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';} else { vizElement.style.width='100%';vizElement.style.height='877px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>
<p></br></p>
<p>And I did the same thing using oil data in <a href="https://public.tableau.com/views/USEIAOilProduction/dashFrackingStatesOil?:language=en-US&amp;publish=yes&amp;:display_count=n&amp;:origin=viz_share_link">Tableau Public</a>.</p>
<pre class="r"><code>read_html(&quot;oil_fracking_states.html&quot;)</code></pre>
<p><div class='tableauPlaceholder' id='viz1627575838492' style='position: relative'><noscript><a href='#'><img alt='dashFrackingStatesOil ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;US&#47;USEIAOilProduction&#47;dashFrackingStatesOil&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='USEIAOilProduction&#47;dashFrackingStatesOil' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;US&#47;USEIAOilProduction&#47;dashFrackingStatesOil&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='en-US' /><param name='filter' value='publish=yes' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1627575838492');                    var vizElement = divElement.getElementsByTagName('object')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.minWidth='420px';vizElement.style.maxWidth='650px';vizElement.style.width='100%';vizElement.style.minHeight='587px';vizElement.style.maxHeight='887px';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.minWidth='420px';vizElement.style.maxWidth='650px';vizElement.style.width='100%';vizElement.style.minHeight='587px';vizElement.style.maxHeight='887px';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';} else { vizElement.style.width='100%';vizElement.style.height='827px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script> </br></p>
</div>
<div id="linear-regression-model" class="section level2">
<h2>Linear Regression Model</h2>
<p>Now join the CRP and Oil Production data and compare the two variables using linear regression.</p>
<pre class="r"><code># Note - inner join filters both tables
DT &lt;- merge(oil_dt, crp_dt, by = c(&quot;state&quot;, &quot;year&quot;))
DT &lt;- DT[, .(avg_barrels_per_day = mean(avg_barrels_per_day), 
             acres = sum(acres)), 
         by = year]
ggplot(DT, aes(x = avg_barrels_per_day, y = acres)) + 
  geom_point() + 
  stat_summary(fun.data = mean_cl_normal) + 
  geom_smooth(method = &quot;lm&quot;, formula = y~x)</code></pre>
<pre><code>## Warning: Removed 34 rows containing missing values (geom_segment).</code></pre>
<p><img src="analysis_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>We can see there are a couple of outliers. Since fracking didn’t start until the 1980’s, let’s filter out dates before 1990 and plot the linear model again.</p>
<pre class="r"><code>DT &lt;- DT[year &gt;= 1990]
ggplot(DT, aes(x = avg_barrels_per_day, y = acres)) + 
  geom_point() + 
  stat_summary(fun.data = mean_cl_normal) + 
  geom_smooth(method = &quot;lm&quot;, formula = y~x) +
  labs(y = &quot;Acres Enrolled in CRP&quot;, x = &quot;Avg Barrel per Day (1000&#39;s)&quot;)</code></pre>
<pre><code>## Warning: Removed 30 rows containing missing values (geom_segment).</code></pre>
<p><img src="analysis_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>Much better! Now we can see there is a distinct linear trend between the number of acres enrolled in the Conservation Reserve Program and the average quantity (1,000’s barrels) of oil produced within the same states.</p>
<p>More precisely, <b>87.81%</b> of the variance in the acres enrolled in CRP can be explained by the variance in the average number of barrels of crude produced in these same states according to our model.</p>
<pre class="r"><code>mod &lt;- lm(acres ~ avg_barrels_per_day, DT)
summary(mod)</code></pre>
<pre><code>## 
## Call:
## lm(formula = acres ~ avg_barrels_per_day, data = DT)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1554421  -640077   268381   475988  2142412 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)         20670853     351148   58.87  &lt; 2e-16 ***
## avg_barrels_per_day   -18681       1315  -14.21 2.53e-14 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 904900 on 28 degrees of freedom
## Multiple R-squared:  0.8781, Adjusted R-squared:  0.8738 
## F-statistic: 201.8 on 1 and 28 DF,  p-value: 2.526e-14</code></pre>
</div>
<div id="log-linear-regression-model" class="section level2">
<h2>Log-Linear Regression Model</h2>
<p>But can we do better? Note that the values for our dependent variable (Acres Enrolled in CRP) are much larger than the values for our independent variable (Avg Barrel per Day in 1000’s). Let’s try taking the <a href="https://en.wikipedia.org/wiki/Natural_logarithm">natural log</a> of our dependent variable to improve the scale and plot the new values in a log-linear model.</p>
<pre class="r"><code>DT[, ln_acres := log(acres)]
ggplot(DT, aes(x = avg_barrels_per_day, y = ln_acres)) + 
  geom_point() + 
  geom_smooth(method = &quot;lm&quot;, formula = y ~ x) +
  labs(y = &quot;LN(Acres Enrolled in CRP)&quot;, x = &quot;Avg Barrel per Day (1000&#39;s)&quot;)</code></pre>
<p><img src="analysis_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>Now let’s check the log-linear model.</p>
<pre class="r"><code>mod &lt;- lm(ln_acres ~ avg_barrels_per_day, DT)
summary(mod)</code></pre>
<pre><code>## 
## Call:
## lm(formula = ln_acres ~ avg_barrels_per_day, data = DT)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.09945 -0.03593  0.01164  0.03722  0.13649 
## 
## Coefficients:
##                       Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)          1.689e+01  2.135e-02  791.17  &lt; 2e-16 ***
## avg_barrels_per_day -1.276e-03  7.996e-05  -15.96 1.37e-15 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.05502 on 28 degrees of freedom
## Multiple R-squared:  0.901,  Adjusted R-squared:  0.8974 
## F-statistic: 254.8 on 1 and 28 DF,  p-value: 1.368e-15</code></pre>
<p>Not bad. We can see the log-linear model is a little better than the linear model. According to our log-linear model, <b>90.1%</b> of the variance in the natural log of acres enrolled in CRP can be explained by the variance in the average number of barrels of crude produced in these same states.</p>
</div>
<div id="log-log-regression-model" class="section level2">
<h2>Log-Log Regression Model</h2>
<p>But what if we take the natural log of our independent variable as well and compare the values using a log-log model?</p>
<pre class="r"><code>DT[, ln_avg_barrels_per_day := log(avg_barrels_per_day)]
ggplot(DT, aes(x = ln_avg_barrels_per_day, y = ln_acres)) + 
  geom_point() + 
  geom_smooth(method = &quot;lm&quot;, formula = y ~ x) +
  labs(y = &quot;LN(Acres Enrolled in CRP)&quot;, x = &quot;LN(Avg Barrel per Day (1000&#39;s))&quot;)</code></pre>
<p><img src="analysis_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>And let’s create the log-log model.</p>
<pre class="r"><code>mod &lt;- lm(ln_acres ~ ln_avg_barrels_per_day, DT)
summary(mod)</code></pre>
<pre><code>## 
## Call:
## lm(formula = ln_acres ~ ln_avg_barrels_per_day, data = DT)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.09811 -0.02812 -0.01148  0.03973  0.08503 
## 
## Coefficients:
##                        Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)            18.56566    0.11294  164.38   &lt;2e-16 ***
## ln_avg_barrels_per_day -0.36881    0.02103  -17.54   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.0505 on 28 degrees of freedom
## Multiple R-squared:  0.9166, Adjusted R-squared:  0.9136 
## F-statistic: 307.6 on 1 and 28 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Now let’s check the residuals - they should be approximately normally distributed.</p>
<pre class="r"><code>.residuals &lt;- mod$residuals
hist(.residuals)</code></pre>
<p><img src="analysis_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>Hey-oh now we’re coookin!</p>
</div>
<div id="results" class="section level2">
<h2>Results</h2>
<p>According to our log-log model <b>91.66%</b> of the variance in the natural log of acres enrolled in CRP can be explained by the variance in the natural log of average number of barrels of crude produced in these same states.</p>
<p>Furthermore, since this is a <a href="https://stats.idre.ucla.edu/other/mult-pkg/faq/general/faqhow-do-i-interpret-a-regression-model-when-some-variables-are-log-transformed/">log-log model</a> we know that the slope coefficient is the <a href="https://stackoverflow.com/a/56614010/8623742">elasticity</a>.</p>
<p>Therefore, according to our log-log model, a <b>1% increase</b> in the Avg Barrel Produced per Day in 1000’s will result in an approximate <b>0.3688% decrease</b> in the Acres Enrolled in CRP for states where hydraulic fracturing is utilized for oil production.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
